### ISSUE TITLE
Add support for "bright" colors

### ISSUE THREAD

**Issue by Fuco1** [rejeep/ansi.el#2]
> Later terminals added the ability to directly specify the "bright" colors with 90-97 and 100-107.

https://en.wikipedia.org/wiki/ANSI_escape_code#Colors

I think this is pretty much 100% supported nowadays.

**Comment by Fuco1** [comment]
Seems like `(bold (black "already present"))` produces gray so maybe this is already implemented in this way?

**Comment by rejeep** [comment]
I added you as a collaborator!

> Seems like (bold (black "already present")) produces gray so maybe this is already implemented in this way?

Not intentional

**Comment by Fuco1** [comment]
It seems it is actually the same thing

```
Examples: to get black letters on white background use ESC[30;47m, to get red use ESC[31m, to get bright red use ESC[1;31m. To reset colors to their defaults, use ESC[39;49m (not supported on some terminals), or reset all attributes with ESC[0m. Later terminals added the ability to directly specify the "bright" colors with 90–97 and 100–107.
```

(from linked wiki page).

**Comment by Fuco1** [comment]
Actually, I guess it is not exactly the same, because bold and color has the `m` token there twice.  I will add the bright colors.
