### ISSUE TITLE
Broke Cask for Emacs < 24.4

### ISSUE THREAD

**Issue by Silex** [rejeep/ansi.el#6]
Hello,

FYI https://github.com/rejeep/ansi.el/commit/bd9076cc360ac3880879975cf0721f8c24c91aec bumped the requirements to `24.4`, thus forcing Cask to also bump its requirements.

https://github.com/cask/cask/issues/480

Just linking the two so future people know.

**Comment by Fuco1** [comment]
I've removed the tests for 24.*, it's super archaic at this point and usage is probably <0.5%
